import { Geist, Geist_Mono } from "next/font/google";
import "@/style/globals.css";
import { Providers } from "@/components/other/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Providers>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <div className="flex items-center justify-center w-full h-screen p-2 gap-2 border-2 border-dark border-dashed">
            {children}
          </div>
        </body>
      </html>
    </Providers>
  );
}
